### ISSUE TITLE
README.md Update - High DPI Scaling In PyQt5

### ISSUE THREAD

**Issue by MRRIZK** [adamtheone/canDrive#25]
On high resolution monitors the layout of the GUI is not correct when scaling is enabled. Potentially add functionality to support High DPI monitors ie: check box and subsequent restart or add the below to the readme file for others to know where to change.

**canSniffer_ui.py (Change to)**

from PyQt5 import QtCore, QtGui, QtWidgets

_QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True) #enable highdpi scaling
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True) #use highdpi icons_

PS: Adding the above worked for me. No idea if it is the correct way to achieve the desired outcome. Thanks!

**Comment by adamtheone** [comment]
Added and pushed. Thanks!
