### ISSUE TITLE
GUI on Silicone Mac

### ISSUE THREAD

**Issue by gateseee** [adamtheone/canDrive#37]
Is it possible, to use the GUI somehow on Apple Silicon Mac (MBP 2023 M2 Pro). 
When installing the depencies i am getting errors relating to PyQT5. 

It seems like PyQT5 is not nativly supported on Silicon Mac's. 
I am not into Python right now, but updating to PYQT6 should work on Silicon.

Does by any chance someone have a working/valid workaround? 

Br

**Comment by adamtheone** [comment]
Personally I don't have experience with Macs, but you should look for answers on PyQt related forums. Or try it with PyQt6, maybe that works.

**Comment by gateseee** [comment]
Thanks for the fast response. Usually im also not that much into Macs, but i recently got one for developing outside the house thats why i have to struggle with such things now. On my Windows Laptop/Desktop everything works fine.

I will try to get it to work somehow, and will post the solution here, if i am able to get it to work.
