### ISSUE TITLE
Please help reverse effects of canbus hack. 

### ISSUE THREAD

**Issue by ghost** [adamtheone/canDrive#38]
Hi Adam, 

I've watched your internet tutorials with interested, hence the approach here.

Some help is much needed and appreciated. I'm a 45 year old disabled man that lives in Faringdon, Oxfordshire. The disabilities are severe sensory PTSD, agoraphobia and psychogenic hyperventilation. 

Since earlier this year the motability Golf has been hacked by people with anti-disability vendettas. They've accessed the canbus remotely so the suspension wallows, shudders and porpoises over undulations. Extensive research was conducted and I'm desperate for the hacking to stop. It's ruining what little quality of life there is. 

Can Savvy seems to be able to access various canbus to alter settings? Please can you advise how it can be used to reverse the affects to the suspension? They've also altered another canbus so there's excessive noise and vibration through pedals and steering. Dealer resets haven't worked. All help is much appreciated. It would be much appreciated if we could arrange a video call so I can be shown how to address the issues. 

Many thanks in advance,

Josh Ross

**Comment by adamtheone** [comment]
Dear Josh, 

If this is really the case, I'm very sorry for what happened. Unfortunately, this topic is beyond my expertise or the goal of this library. Luckily, I see that you already received some tips and some help in the SavvyCAN discussion. I wish you the best of luck, but unfortunately, I cannot provide additional help.

Best,
Adam
