### ISSUE TITLE
no any data recived

### ISSUE THREAD

**Issue by MohamedAbdelrehem** [adamtheone/canDrive#39]
hey adam,
first of all thanks for this awesome project I learned a lot from it

I am using **Chevrolet Optra 2010** which is known by Lacetti
I connected to OBD-II to pin 6 and 14
changed the oscillator crystal clock to #define MCP2515_DEFAULT_CLOCK_FREQUENCY 8e6 in MCP2515.h
I tried the example codes (RPM and read) plus your code 
all of them don't give me any reading (not even dump unreadable frames or data)

any suggestions or solutions?

**Comment by adamtheone** [comment]
answered in the other thread (issue #9)
