### ISSUE TITLE
i cannot change 29bit

### ISSUE THREAD

**Issue by gddam** [adamtheone/canDrive#45]
i caanot open your link https://github.com/adamtheone/canDrive/tree/29bit_id_support. please update

**Comment by adamtheone** [comment]
this branch has been merged into 'main' by two PRs:
https://github.com/adamtheone/canDrive/commit/8622a349ebc11c3faad36d10bdd7088ae0b9d9ba
https://github.com/adamtheone/canDrive/commit/486ce3c1a3d23cd56ec4cd4eb9ac0d6ebfda074c
