### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Stanrighttoleft** [adamtheone/canDrive#46]
I am quite new to this, is this sniffer .ino file for loading to Arduino uno to work, but what is the mcp2515.CPP and mcp2515.h file for? How should I use this code to work to read the canbus signal? Sorry for created issue but I can't work out how to use, thank you.

**Comment by adamtheone** [comment]
I can't provide detailed support, but I think my [youtube videos](https://www.youtube.com/playlist?list=PLNiFaO8hU1z0o_6DSxk-jcVAM3UCUR-pY) explain everything to great detail. If those are not enough, I suggest getting up to speed with some other tutorials about the Arduino ecosystem.
